CLIP_TITLE = 'Title'
CLIP_TITLE_EDIT = 'Editted Title'
CLIP_DESCRIPTION = 'Description'
CLIP_DESCRIPTION_EDIT = 'Editted Description'
CLIP_URL_YOUTUBE = 'https://www.youtube.com/watch?v=2VMgxLLbYEs'
CLIP_URL_TWITCH = 'https://clips.twitch.tv/DeafFrailWitchWoofer'
CLIP_URL_TWITTER = 'https://twitter.com/Krankdud/status/957171192980373507'
CLIP_TAGS = 'tag1,tag2,tag3'
CLIP_TAGS_EDIT = 'edit1,edit2,edit3'

USER_NAME = 'user'
USER_PASSWORD = 'Password1'
USER_EMAIL = 'user@email.com'
OTHER_USER_NAME = 'user2'
OTHER_USER_PASSWORD = 'Password1'
OTHER_USER_EMAIL = 'user2@email.com'